# Generated by Django 5.0.4 on 2024-12-04 22:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongESRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_name', models.CharField(max_length=50)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('youtube_video', models.CharField(default='', max_length=1000)),
                ('description', models.TextField(default='', max_length=500)),
                ('duration', models.TextField(default='', max_length=100)),
                ('recently_added', models.BooleanField(default=False)),
                ('release_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('authors', models.ManyToManyField(to='music.songauthors')),
                ('categories', models.ManyToManyField(to='music.songcategory')),
                ('ESRB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.songesrb')),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.songproduction')),
            ],
        ),
        migrations.CreateModel(
            name='SongReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_reviews', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_reviews', to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='UserSongsLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs', models.ManyToManyField(related_name='songs_libraries', to='music.song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='songs_library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
