# Generated by Django 5.0.4 on 2024-12-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='production',
        ),
        migrations.RemoveField(
            model_name='songesrb',
            name='image',
        ),
        migrations.DeleteModel(
            name='SongProduction',
        ),
    ]
