# Generated by Django 5.0.4 on 2024-11-05 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameESRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_id', models.IntegerField()),
                ('review_id', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('author_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('platform', models.ManyToManyField(to='games.gameplatform')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('youtube_video', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=500)),
                ('developer', models.CharField(default='', max_length=120)),
                ('publisher', models.CharField(default='', max_length=120)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('recently_added', models.BooleanField(default=False)),
                ('release_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('budget', models.ManyToManyField(to='games.gamebudget')),
                ('category', models.ManyToManyField(to='games.gamecategory')),
                ('ESRB', models.ManyToManyField(to='games.gameesrb')),
                ('platform', models.ManyToManyField(to='games.gameplatform')),
                ('reviews', models.ManyToManyField(blank=True, to='games.gamereview')),
            ],
        ),
    ]
