# Generated by Django 5.0.4 on 2024-12-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamebudget',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gameesrb',
            name='image',
        ),
    ]
