# Generated by Django 5.0.4 on 2024-11-07 15:51

from django.db import migrations
from django.utils.text import slugify


def populate_game_slugs(apps, schema_editor):
    Game = apps.get_model('games', 'Game')
    for game in Game.objects.all():
        if not game.slug:
            base_slug = slugify(game.name)
            slug = base_slug
            num = 1

            while Game.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{num}"
                num += 1

            game.slug = slug
            game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_slug'),
    ]

    operations = [
        migrations.RunPython(populate_game_slugs),
    ]
