# Generated by Django 5.0.4 on 2024-11-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_populate_game_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='platform',
            new_name='platforms',
        ),
    ]
