# Generated by Django 5.0.4 on 2024-11-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_category_game_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebudget',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
