# Generated by Django 5.0.4 on 2024-11-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gamebudget_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
