# Generated by Django 5.0.4 on 2024-11-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_game_developer_remove_game_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ESRB',
        ),
        migrations.RemoveField(
            model_name='game',
            name='budget',
        ),
        migrations.AddField(
            model_name='game',
            name='ESRB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gameesrb'),
        ),
        migrations.AddField(
            model_name='game',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamebudget'),
        ),
    ]
