# Generated by Django 5.0.4 on 2024-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_game_esrb_remove_game_budget_game_esrb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(to='games.gamedeveloper'),
        ),
    ]
