# Generated by Django 5.0.4 on 2024-11-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_game_score_remove_gamereview_author_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereview',
            name='author',
        ),
    ]
