# Generated by Django 5.0.4 on 2024-11-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_gamereview_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereview',
            name='review_id',
        ),
    ]
