# Generated by Django 5.0.4 on 2024-12-01 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_usergameslibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='gamereview',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='gamereview',
            name='game_name',
        ),
        migrations.AddField(
            model_name='gamereview',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_reviews', to='games.game'),
        ),
    ]
