# Generated by Django 5.0.4 on 2024-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
