# Generated by Django 5.0.4 on 2024-12-04 20:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowActors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowESRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_name', models.CharField(max_length=50)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowWriters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('youtube_video', models.CharField(default='', max_length=1000)),
                ('description', models.TextField(default='', max_length=500)),
                ('episode_duration', models.TextField(default='', max_length=100)),
                ('episodes', models.IntegerField(default=0)),
                ('recently_added', models.BooleanField(default=False)),
                ('release_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('actors', models.ManyToManyField(to='shows.showactors')),
                ('categories', models.ManyToManyField(to='shows.showcategory')),
                ('director', models.ManyToManyField(to='shows.showdirectors')),
                ('ESRB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.showesrb')),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.showproduction')),
                ('writers', models.ManyToManyField(to='shows.showwriters')),
            ],
        ),
        migrations.CreateModel(
            name='ShowReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_reviews', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show_reviews', to='shows.show')),
            ],
        ),
        migrations.CreateModel(
            name='UserShowsLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shows', models.ManyToManyField(related_name='shows_libraries', to='shows.show')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shows_library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
