# Generated by Django 5.0.4 on 2024-12-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='production',
        ),
        migrations.RemoveField(
            model_name='showactors',
            name='character',
        ),
        migrations.RemoveField(
            model_name='showdirectors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='showesrb',
            name='image',
        ),
        migrations.RemoveField(
            model_name='showwriters',
            name='image',
        ),
        migrations.DeleteModel(
            name='ShowProduction',
        ),
    ]
