# Generated by Django 5.0.4 on 2024-12-03 00:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieActors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieESRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_name', models.CharField(max_length=50)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieWriters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('youtube_video', models.CharField(default='', max_length=1000)),
                ('description', models.TextField(default='', max_length=500)),
                ('recently_added', models.BooleanField(default=False)),
                ('release_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('actors', models.ManyToManyField(to='movies.movieactors')),
                ('categories', models.ManyToManyField(to='movies.moviecategory')),
                ('director', models.ManyToManyField(to='movies.moviedirectors')),
                ('ESRB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movieesrb')),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movieproduction')),
                ('writers', models.ManyToManyField(to='movies.moviewriters')),
            ],
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_reviews', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='UserMoviesLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(related_name='movies_libraries', to='movies.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movies_library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
