# Generated by Django 5.0.4 on 2024-12-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermovieslibrary',
            old_name='games',
            new_name='movies',
        ),
    ]
