# Generated by Django 5.0.4 on 2024-12-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_games_usermovieslibrary_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production',
        ),
        migrations.RemoveField(
            model_name='moviedirectors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movieesrb',
            name='image',
        ),
        migrations.RemoveField(
            model_name='moviewriters',
            name='image',
        ),
        migrations.DeleteModel(
            name='MovieProduction',
        ),
    ]
