# Generated by Django 5.0.4 on 2024-12-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_production_remove_moviedirectors_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieactors',
            name='character',
        ),
    ]
