# Generated by Django 5.0.4 on 2024-07-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
