# Generated by Django 5.0.4 on 2024-10-09 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='recently_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
